name: Update CloudFormation stack by only changing its parameters
description: >
  Updates CloudFormation stack by updating its parameters while preserving all other settings.

inputs:
  stack:
    description: CloudFormation stack name
    required: true
  parameters:
    description: >
      Newline-separated parameters to change in the Name=Value format.
      Stack parameters not set here would retain their existing values.
    required: true

runs:
  using: docker
  image: docker://ghcr.io/doist/update-cloudformation-stack:latest
  args:
    - '-stack=${{ inputs.stack }}'
