name: Update CloudFormation stack by changing a single parameter
description: >
  Updates a single parameter in an existing CloudFormation stack while preserving all other settings.

inputs:
  stack:
    description: CloudFormation stack name
    required: true
  key:
    description: Name of stack parameter to update
    required: true
  value:
    description: New value to set for a given parameter
    required: true

runs:
  using: docker
  image: docker://ghcr.io/artyom/update-cloudformation-stack:latest
  args:
    - '-stack=${{ inputs.stack }}'
    - '-key=${{ inputs.key }}'
    - '-value=${{ inputs.value }}'
